# Generated by Django 4.1.13 on 2024-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
